name: first-action 
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: |
          echo "welcome to github actions"
          echo "this is the new line"
          
    
